site_name: Text-Fabric
site_description: >- 
  Text-Fabric is a Python3 package for Text plus Annotations.
  It provides a data model,
  a text file format,
  a binary format,
  an API,
  and apps
  for (ancient) text plus
  (linguistic) annotations.

site_url: 'https://annotation.github.io/text-fabric/'
site_author: Dirk Roorda

repo_name: annotation/text-fabric
repo_url: 'https://github.com/annotation/text-fabric/'
