site_name: Text-Fabric
site_description: >- 
  Text-Fabric is a Python3 package for Text plus Annotations.
  It provides a data model,
  a text file format,
  a binary format,
  an API,
  and apps
  for (ancient) text plus
  (linguistic) annotations.

site_url: 'https://annotation.github.io/text-fabric/'
site_author: Dirk Roorda

repo_url: 'https://github.com/annotation/text-fabric/'

theme:
  name: dans
  logo: 'images/tf-small.png'
  favicon: 'images/icon/favicon.ico'
  development: false

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Dans-labs
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - markdownextradata
  - search
  - minify:
      minify_html: true

nav:
  - Home: 'index.md'
  - About:
    - Install: 'About/Install.md'
    - Corpora: 'About/Corpora.md'
    - Faq: 'About/Faq.md'
    - News: 'About/News.md'
    - Older: 'About/Older.md'
  - Use:
    - Use: 'Use/Use.md'
    - Browser: 'Use/Browser.md'
    - Search: 'Use/Search.md'
    - Advanced: 'Use/UseX.md'
  - Api:
    - Apps: 'Api/App.md'
    - Data flow:
      - Data: 'Api/Data.md'
      - Repo: 'Api/Repo.md'
    - Core:
      - 'TF': 'Api/Fabric.md'
      - 'E/F - (Edge-)Features': 'Api/Features.md'
      - 'N - Nodes': 'Api/Nodes.md'
      - 'L - Locality': 'Api/Locality.md'
      - 'T - Text': 'Api/Text.md'
      - 'S - Search': 'Api/Search.md'
      - 'C - Computed': 'Api/Computed.md'
      - 'Miscellaneous': 'Api/Misc.md'
      - 'Lib': 'Api/Lib.md'
      - 'Helpers': 'Api/Helpers.md'
    - Compose:
      - 'Combining': 'Api/Compose.md'
  - Writing:
    - Arabic: 'Writing/Arabic.html'
    - Hebrew: 'Writing/Hebrew.html'
    - Syriac: 'Writing/Syriac.html'
    - Transcription: 'Writing/Transcription.md'
  - Model:
    - Data: 'Model/Data-Model.md'
    - Format: 'Model/File-formats.md'
    - Tweaks: 'Model/Optimizations.md'
    - Search: 'Model/Search.md'
  - Create:
    - 'Convert': 'Create/Convert.md'
    - 'Pattern': 'Create/CreateTF.md'
    - 'Example data': 'Create/ExampleText.md'
    - 'MQL': 'Create/MQL.md'
  - Server:
    - Kernel: 'Server/Kernel.md'
    - Web: 'Server/Web.md'
    - Common: 'Server/Common.md'
  - Code:
    - 'Overview' : 'Code/Overview.md'
    - 'Tests' : 'Code/Tests.md'
    - 'Stats (overall)' : 'Code/Stats.md'
    - 'Stats (TF-toplevel)' : 'Code/StatsToplevel.md'
    - 'Stats (TF-core)' : 'Code/StatsCore.md'
    - 'Stats (TF-search)' : 'Code/StatsSearch.md'
    - 'Stats (TF-convert)' : 'Code/StatsConvert.md'
    - 'Stats (TF-compose)' : 'Code/StatsCompose.md'
    - 'Stats (TF-writing)' : 'Code/StatsWriting.md'
    - 'Stats (TF-server)' : 'Code/StatsServer.md'
    - 'Stats (TF-app support)' : 'Code/StatsApplib.md'
    - 'Stats (TF-apps)' : 'Code/StatsApps.md'
    - 'Stats (Tests)' : 'Code/StatsTest.md'
  - Implementation:
    - Apps: 'Implementation/Apps.md'
    - Setup: 'Implementation/Setup.md'
    - Data: 'Implementation/Data.md'
    - Display: 'Implementation/Display.md'
    - Highlight : 'Implementation/Highlight.md'
    - Links : 'Implementation/Links.md'
    - Search : 'Implementation/Search.md'
    - Tables : 'Implementation/Tables.md'
    - Helpers : 'Implementation/Helpers.md'

extra:
  b_apps: tf/apps
  b_convert: tf/convert
  b_core: tf/core
  b_search: tf/search
  b_server: tf/server
  b_static: tf/server/static
  b_views: tf/server/views
  b_writing: tf/writing
  c_api: tf/core/api.py
  c_app: tf/app.py
  c_applib: tf/applib
  c_appapi: tf/applib/api.py
  c_appcondense: tf/applib/condense.py
  c_appdata: tf/applib/data.py
  c_appdisplay: tf/applib/display.py
  c_appdisplaysettings: tf/applib/displaysettings.py
  c_apphelpers: tf/applib/helpers.py
  c_apphighlight: tf/applib/highlight.py
  c_applinks: tf/applib/links.py
  c_appsearch: tf/applib/search.py
  c_appsections: tf/applib/sections.py
  c_apptables: tf/applib/tables.py
  c_appmake: tf/applib/make.py
  c_bhsa_app: tf/apps/bhsa/app.py
  c_bhsa_config: tf/apps/bhsa/config.py
  c_bhsa_css: tf/apps/bhsa/static/display.css
  c_bhsa_logo: tf/apps/bhsa/static/logo.png
  c_common: tf/server/common.py
  c_data: tf/core/data.py
  c_fabric: tf/fabric.py
  c_graph: tf/search/graph.py
  c_helpers: tf/core/helpers.py
  c_kernel: tf/server/kernel.py
  c_locality: tf/core/locality.py
  c_mql: tf/convert/mql.py
  c_parameters: tf/parameters.py
  c_peshitta_app: tf/apps/peshitta/app.py
  c_peshitta_config: tf/apps/peshitta/config.py
  c_peshitta_css: tf/apps/peshitta/static/display.css
  c_peshitta_logo: tf/apps/peshitta/static/logo.png
  c_prepare: tf/core/prepare.py
  c_relations: tf/search/relations.py
  c_search: tf/search/search.py
  c_searchexe: tf/search/searchexe.py
  c_semantics: tf/search/semantics.py
  c_spin: tf/search/spin.py
  c_start: tf/server/start.py
  c_stitch: tf/search/stitch.py
  c_syntax: tf/search/syntax.py
  c_syrnt_app: tf/apps/syrnt/app.py
  c_syrnt_config: tf/apps/syrnt/config.py
  c_syrnt_css: tf/apps/syrnt/static/display.css
  c_syrnt_logo: tf/apps/syrnt/static/logo.png
  c_text: tf/core/text.py
  c_timestamp: tf/core/timestamp.py
  c_transcription: tf/writing/transcription.py
  c_uruk_app: tf/apps/uruk/app.py
  c_uruk_config: tf/apps/uruk/config.py
  c_uruk_css: tf/apps/uruk/static/display.css
  c_uruk_logo: tf/apps/uruk/static/logo.png
  c_web: tf/server/web.py
  c_zipdata: tf/applib/zipdata.py
  an: https://github.com/annotation
  antut: https://github.com/annotation/tutorials
  anaconda: https://www.anaconda.com/download
  anapp: https://github.com/annotation/app-
  arxiv: https://arxiv.org
  arxiv1: https://arxiv.org/abs/1501.01866
  arxiv2: https://arxiv.org/abs/1410.0286 
  arxiv3: https://arxiv.org/abs/1412.6069
  arxiv4: https://arxiv.org/abs/1603.01541
  banksphlebas: https://read.amazon.com/kp/kshare?asin=B002TXZRQI&id=NpPGzf_HT5aADabyiDDSIQ&reshareId=RZ91SGMZJPWK9S1Y4EZX&reshareChannel=system
  bhsaabout: https://etcbc.github.io/bhsa/
  bottle: https://bottlepy.org 
  bruder12: http://www.nuernberger-hausbuecher.de/75-Amb-2-317-4-v/data
  cdli: https://cdli.ucla.edu
  codingdoi: https://doi.org/10.1163/24523666-01000011
  conncomp: http://www.analytictech.com/networks/graphtheory.htm
  cssflex: https://css-tricks.com/snippets/css/a-guide-to-flexbox
  dans: https://dans.knaw.nl/en
  dlgh: https://github.com/Dans-labs
  doedens: https://books.google.nl/books?id=9ggOBRz1dO4C
  dssabout: https://github.com/ETCBC/dss/blob/master/docs/about.md
  emdros: https://emdros.org
  etcbc: http://etcbc.nl
  etcbcgh: https://github.com/etcbc
  etcbcnb: https://nbviewer.jupyter.org/github/etcbc
  faqhint1: https://www.computerhope.com/issues/ch000549.htm
  flask: http://flask.pocoo.org/docs/1.0/
  fontlib: https://fontlibrary.org
  ghapi: https://developer.github.com/v3/
  ghappreg: https://github.com/settings/applications/new
  ghrate: https://developer.github.com/v3/#rate-limiting
  ghissues: https://github.com/annotation/text-fabric/issues
  git: https://git-scm.com/downloads 
  jensengh: https://github.com/ch-jensen/Semantic-mapping-of-participants
  jquery: https://api.jquery.com
  jup: https://jupyter.org
  lfgh: https://github.com/annotation/laf-fabric
  mkdocs: https://mkdocs.readthedocs.io/en/stable/
  moz_color: https://developer.mozilla.org/en-US/docs/Web/CSS/color_value 
  moz_details: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details
  moz_length: https://developer.mozilla.org/en-US/docs/Web/CSS/length 
  moz_input: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
  nena: https://nena.ames.cam.ac.uk
  ninogh: https://github.com/Nino-cunei
  ninonb: https://nbviewer.jupyter.org/github/Nino-cunei
  node: https://nodejs.org/en/
  oldbabylonianabout: https://github.com/Nino-cunei/oldbabylonian/blob/master/docs/about.md
  oldassyrianabout: https://github.com/Nino-cunei/oldassyrian/blob/master/docs/about.md
  oracc: http://oracc.museum.upenn.edu/doc/help
  patristicsabout: https://github.com/pthu/patristics
  peshittaabout: https://github.com/ETCBC/peshitta/blob/master/docs/about.md
  python: https://docs.python.org/3
  pythond: https://www.python.org/downloads/
  quranabout: https://github.com/q-ran/quran/blob/master/docs/about.md
  rpyc: https://github.com/tomerfiliba/rpyc
  rpycdocboxing: https://rpyc.readthedocs.io/en/latest/docs/theory.html#boxing
  rpycdocservices: https://rpyc.readthedocs.io/en/latest/docs/services.html#services 
  pres1: http://www.slideshare.net/dirkroorda/text-fabric
  pthugh: https://github.com/pthu
  sbl1: https://global-learning.org/mod/forum/discuss.php?d=22
  shebanq: https://shebanq.ancient-data.org
  syrntabout: https://github.com/ETCBC/syrnt/blob/master/docs/about.md
  tfdgh: https://github.com/annotation/text-fabric-data
  tfdnb: https://nbviewer.jupyter.org/github/annotation/text-fabric-data/blob/master
  tfdghb: https://github.com/annotation/text-fabric-data/blob/master 
  tfdght: https://github.com/annotation/text-fabric-data/tree/master 
  tfdoi: https://doi.org/10.5281/zenodo.592193
  tfgh: https://github.com/annotation/text-fabric
  tfghb: https://github.com/annotation/text-fabric/blob/master
  tfght: https://github.com/annotation/text-fabric/tree/master 
  tfnb: https://nbviewer.jupyter.org/github/annotation/text-fabric/blob/master
  tfbanks: https://nbviewer.jupyter.org/github/annotation/banks/blob/master
  tfpp: https://pypi.org/project/text-fabric/ 
  tischtf: https://github.com/codykingham/tischendorf_tf
  tutnb: https://nbviewer.jupyter.org/github/annotation/tutorials/blob/master
  tutnbt: https://nbviewer.jupyter.org/github/annotation/tutorials/tree/master
  ubiq1: https://www.ubiquitypress.com/site/chapters/10.5334/bbi.18/
  urukabout: https://github.com/Nino-cunei/uruk/blob/master/docs/about.md
  weave: https://sew4home.com/tips-resources/buying-guide/all-about-fabric-weaves-tutorial
  wikip: https://en.wikipedia.org/wiki
  zenodo: https://zenodo.org
