site_name: Text-Fabric
site_description: >- 
  Text-Fabric is a Python3 package for Text plus Annotations.
  It provides a data model,
  a text file format,
  a binary format,
  an API,
  and apps
  for (ancient) text plus
  (linguistic) annotations.

site_url: 'https://annotation.github.io/text-fabric/'
site_author: Dirk Roorda

repo_name: annotation/text-fabric
repo_url: 'https://github.com/annotation/text-fabric/'

theme:
  name: dans
  logo: 'images/tf-small.png'
  favicon: 'images/icon/favicon.ico'
  development: false
  feature:
    tabs: true

strict: false

markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Dans-labs
      repo: mkdocs-dans
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - markdownextradata
  - search
  - minify:
      minify_html: true

nav:
  - Home: 'index.md'
  - About:
    - Install: 'About/Install.md'
    - Corpora: 'About/Corpora.md'
    - Faq: 'About/Faq.md'
    - Story: 'About/Story.md'
    - News: 'About/News.md'
    - Older: 'About/Older.md'
  - Use:
    - Use: 'Use/Use.md'
    - Browser: 'Use/Browser.md'
    - Search: 'Use/Search.md'
    - Advanced: 'Use/UseX.md'
  - Api:
    - Advanced: 'Api/App.md'
    - Core:
      - 'TF': 'Api/Fabric.md'
      - 'E/F - (Edge-)Features': 'Api/Features.md'
      - 'N - Nodes': 'Api/Nodes.md'
      - 'L - Locality': 'Api/Locality.md'
      - 'T - Text': 'Api/Text.md'
      - 'S - Search': 'Api/Search.md'
      - 'C - Computed': 'Api/Computed.md'
      - 'Miscellaneous': 'Api/Misc.md'
      - 'Lib': 'Api/Lib.md'
      - 'Helpers': 'Api/Helpers.md'
    - Data flow:
      - Data: 'Api/Data.md'
      - Repo: 'Api/Repo.md'
      - GitHub: 'Api/Github.md'
    - Compose:
      - 'Combining': 'Api/Compose.md'
  - Writing:
    - Arabic: 'Writing/Arabic.md'
    - Hebrew: 'Writing/Hebrew.md'
    - Syriac: 'Writing/Syriac.md'
    - Transcription: 'Writing/Transcription.md'
  - Model:
    - Data: 'Model/Data-Model.md'
    - Format: 'Model/File-formats.md'
    - Tweaks: 'Model/Optimizations.md'
    - Search: 'Model/Search.md'
  - Create:
    - 'Convert': 'Create/Convert.md'
    - 'Pattern': 'Create/CreateTF.md'
    - 'Example data': 'Create/ExampleText.md'
    - 'MQL': 'Create/MQL.md'
  - Server:
    - Kernel: 'Server/Kernel.md'
    - Web: 'Server/Web.md'
    - Common: 'Server/Common.md'
  - Code:
    - 'Overview' : 'Code/Overview.md'
    - 'Tests' : 'Code/Tests.md'
    - 'Stats (overall)' : 'Code/Stats.md'
    - 'Stats (TF-toplevel)' : 'Code/StatsToplevel.md'
    - 'Stats (TF-core)' : 'Code/StatsCore.md'
    - 'Stats (TF-search)' : 'Code/StatsSearch.md'
    - 'Stats (TF-convert)' : 'Code/StatsConvert.md'
    - 'Stats (TF-compose)' : 'Code/StatsCompose.md'
    - 'Stats (TF-writing)' : 'Code/StatsWriting.md'
    - 'Stats (TF-server)' : 'Code/StatsServer.md'
    - 'Stats (TF-app support)' : 'Code/StatsApplib.md'
    - 'Stats (TF-apps)' : 'Code/StatsApps.md'
    - 'Stats (Tests)' : 'Code/StatsTest.md'
  - Implementation:
    - Apps: 'Implementation/Apps.md'
    - Setup: 'Implementation/Setup.md'
    - Data: 'Implementation/Data.md'
    - Display: 'Implementation/Display.md'
    - Highlight : 'Implementation/Highlight.md'
    - Links : 'Implementation/Links.md'
    - Search : 'Implementation/Search.md'
    - Tables : 'Implementation/Tables.md'
    - Helpers : 'Implementation/Helpers.md'
    - docstrings: 'apidocs/html/tf/index.html'
